import type { DataSourceCatalogEntry } from "./sourceTypes.js";

export const DATA_SOURCE_CATALOG: DataSourceCatalogEntry[] = [
  {
    source_id: "csrc-fund-disclosure",
    source_name: "中国证监会基金电子披露网站",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_reports", "nav_disclosure", "xbrl", "legal_disclosure"],
    recommended_for: ["fund_reports", "official_fund_reports", "fund_meta", "official_evidence"],
    access_method: "official website / disclosure documents",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public disclosure documents respectfully; cache and rate-limit access.",
    priority: 1,
    notes: "Primary authoritative source for public fund disclosure. Provider now probes the official entrypoint and parses report links when reachable; site-protection failures are surfaced as data gaps."
  },
  {
    source_id: "csrc-official",
    source_name: "中国证监会官网",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["regulatory_rules", "market_supervision", "fund_regulation", "official_releases"],
    recommended_for: ["regulatory_context", "policy_evidence", "fund_rule_validation"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use public official releases with source URL and publication date.",
    priority: 2,
    notes: "Useful for regulatory evidence and rule changes; not a NAV source."
  },
  {
    source_id: "amac-public-fund-data",
    source_name: "中国证券投资基金业协会",
    source_type: "fund_meta",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_market_statistics", "manager_info", "industry_reports"],
    recommended_for: ["fund_meta", "industry_baseline", "manager_validation"],
    access_method: "official website / public statistics",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public statistics and disclose source timestamp.",
    priority: 3,
    notes: "Best for industry-level facts and manager/public fund validation."
  },
  {
    source_id: "cninfo-disclosure",
    source_name: "巨潮资讯网",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_announcements", "listed_company_announcements", "fund_reports"],
    recommended_for: ["fund_reports", "official_fund_reports", "holdings_cross_check", "official_announcements"],
    access_method: "official disclosure website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Respect official site rules; prefer documented query endpoints if available.",
    priority: 4,
    notes: "Important official disclosure channel."
  },
  {
    source_id: "fund-company-official-sites",
    source_name: "基金公司官网公告与净值披露",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_reports", "current_nav", "fund_meta", "announcements"],
    recommended_for: ["current_nav", "fund_reports", "official_fund_reports", "fund_meta"],
    access_method: "per-company website adapters",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Company sites differ; adapters need per-site maintenance and source timestamps.",
    priority: 5,
    notes: "Useful cross-check source; requires many adapters."
  },
  {
    source_id: "cmfchina-fund-official",
    source_name: "招商基金官网官方公告与产品详情",
    source_type: "fund_report",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "official_company_notices", "report_notice_refs"],
    recommended_for: ["fund_reports", "official_fund_reports", "fund_meta", "official_evidence"],
    access_method: "official website adapter: https://www.cmfchina.com/web/fundDetail/{fund_code}/index.html",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official company pages respectfully; cache and rate-limit. Report prompt notices are not report bodies.",
    priority: 6,
    notes: "Implemented first per-company adapter. It records official notices/report prompts and points to CSRC fund e-disclosure when referenced."
  },
  {
    source_id: "eastmoney-fund",
    source_name: "东方财富/天天基金基金数据",
    source_type: "nav_history",
    quality_tier: "high",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "nav_history", "rankings", "fund_manager"],
    recommended_for: ["nav_history", "current_nav", "fund_meta"],
    access_method: "public web/API adapter or licensed API if available",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Confirm terms before automated use; cache and rate-limit.",
    priority: 10,
    notes: "Practical first target for NAV history, with official-source cross-check later."
  },
  {
    source_id: "eastmoney-fund-archive",
    source_name: "东方财富/天天基金基金档案",
    source_type: "holdings",
    quality_tier: "high",
    stability: "medium",
    coverage: ["holdings", "fund_reports", "asset_allocation"],
    recommended_for: ["holdings", "fund_report_hints", "cross_source_validation"],
    access_method: "public fund archive pages",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Confirm terms before automated use; cache, rate-limit, and cross-check against official reports.",
    priority: 12,
    notes: "Parses public archive tables for stock and bond holdings."
  },
  {
    source_id: "eastmoney-fund-announcement",
    source_name: "东方财富/天天基金基金公告索引",
    source_type: "fund_report",
    quality_tier: "high",
    stability: "medium",
    coverage: ["fund_reports", "periodic_report_index", "announcement_dates"],
    recommended_for: ["fund_report_refs", "report_freshness", "official_report_discovery"],
    access_method: "public F10 announcement API",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use as a public report index only; cross-check and fetch official disclosure PDFs before strong conclusions.",
    priority: 14,
    notes: "Finds periodic report announcements and IDs, but does not yet parse official report bodies."
  },
  {
    source_id: "manual-csv-import",
    source_name: "人工 CSV 导入",
    source_type: "manual_import",
    quality_tier: "high",
    stability: "high",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings"],
    recommended_for: ["fund_meta", "nav_history", "current_nav", "portfolio_holdings", "bootstrap_validation"],
    access_method: "user/operator upload",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Requires audit trail, file checksum, source declaration, and import timestamp.",
    priority: 20,
    notes: "Implemented as explicit local CSV directory fallback via FUNDSENTINEL_MANUAL_CSV_DIR. Best short-term way to validate real-data flow without scraping."
  },
  {
    source_id: "gov-cn-policy",
    source_name: "中国政府网最新政策",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["latest_policy", "macro_policy_context", "policy_evidence"],
    recommended_for: ["policy_evidence", "macro_context", "Logos_policy_background"],
    access_method: "official JSON endpoint: https://www.gov.cn/zhengce/zuixin/ZUIXINZHENGCE.json",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public policy metadata with publication date and URL; do not infer fund-specific conclusions directly.",
    priority: 28,
    notes: "Maps latest official national policy titles to broad fund themes as weak policy background evidence."
  },
  {
    source_id: "csi-index",
    source_name: "中证指数有限公司",
    source_type: "index_data",
    quality_tier: "high",
    stability: "high",
    coverage: ["index_constituents", "index_history", "index_methodology"],
    recommended_for: ["benchmark", "theme_validation", "industry_mapping"],
    access_method: "official website / licensed data",
    requires_auth: true,
    is_demo: false,
    integration_status: "requires_license",
    legal_note: "Index history/constituents may require license for systematic use.",
    priority: 30,
    notes: "Important for benchmark and theme fund validation."
  },
  {
    source_id: "sse-szse-official",
    source_name: "上交所/深交所官方网站",
    source_type: "news",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["exchange_announcements", "trading_calendar", "market_rules"],
    recommended_for: ["market_calendar", "official_market_events", "policy_evidence"],
    access_method: "official websites",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use public official releases with timestamps and links.",
    priority: 35,
    notes: "Useful supporting source for market calendar and official events."
  },
  {
    source_id: "official-policy-sites",
    source_name: "国务院/发改委/工信部/央行/统计局等官方政策数据",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["policy_evidence", "macro_data", "industry_policy"],
    recommended_for: ["policy_evidence", "macro_context", "industry_logic"],
    access_method: "official websites and public releases",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Prefer official pages; keep publication date and URL.",
    priority: 40,
    notes: "Primary source for Logos hard logic evidence."
  },
  {
    source_id: "ndrc-official",
    source_name: "国家发展改革委",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["industry_policy", "macro_policy", "investment_policy"],
    recommended_for: ["policy_evidence", "industry_logic"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public releases with publication date and URL.",
    priority: 41,
    notes: "Important for industry direction and policy-side hard logic."
  },
  {
    source_id: "miit-official",
    source_name: "工业和信息化部",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["manufacturing_policy", "digital_economy", "industry_data"],
    recommended_for: ["policy_evidence", "industry_logic", "theme_validation"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public releases with publication date and URL.",
    priority: 42,
    notes: "Important for technology, manufacturing, telecom, and digital-economy themes."
  },
  {
    source_id: "pbc-official",
    source_name: "中国人民银行",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["monetary_policy", "rates", "liquidity", "financial_statistics"],
    recommended_for: ["macro_context", "bond_fund_context", "risk_context"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public statistics and releases with timestamps.",
    priority: 43,
    notes: "Important macro source for bond funds and liquidity context."
  },
  {
    source_id: "stats-gov-cn",
    source_name: "国家统计局",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_statistics", "industry_statistics", "economic_indicators"],
    recommended_for: ["macro_context", "industry_logic"],
    access_method: "official website / public statistics",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public statistics and keep release date.",
    priority: 44,
    notes: "Core source for macro and industry baseline data."
  },
  {
    source_id: "mof-official",
    source_name: "财政部",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fiscal_policy", "government_bonds", "budget_data"],
    recommended_for: ["macro_context", "bond_fund_context", "policy_evidence"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public releases with source URL and publication date.",
    priority: 45,
    notes: "Useful for fiscal policy and bond-market context."
  },
  {
    source_id: "safe-official",
    source_name: "国家外汇管理局",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fx_data", "cross_border_capital", "balance_of_payments"],
    recommended_for: ["qdii_context", "macro_context"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public statistics and keep release date.",
    priority: 46,
    notes: "Useful for QDII and exchange-rate related context."
  },
  {
    source_id: "commercial-terminal-api",
    source_name: "Wind/Choice/Tushare/其他授权数据 API",
    source_type: "nav_history",
    quality_tier: "high",
    stability: "high",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings", "fund_manager", "benchmark"],
    recommended_for: ["fund_meta", "current_nav", "nav_history", "holdings", "benchmark", "production_data", "cross_source_validation"],
    access_method: "licensed API",
    requires_auth: true,
    is_demo: false,
    integration_status: "requires_license",
    legal_note: "Use only with proper license and credentials; never hardcode keys.",
    priority: 50,
    notes: "Likely production-grade path if budget allows."
  },
  {
    source_id: "fund-company-site-adapters",
    source_name: "头部基金公司官网适配器集合",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "official_notices", "report_notice_refs"],
    recommended_for: ["official_company_cross_check", "fund_reports", "official_fund_reports", "fund_meta", "current_nav"],
    access_method: "per-company official website adapters",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Each adapter must respect website terms, rate-limit, and keep source URLs.",
    priority: 60,
    notes: "Planned expansion path after the first CMF China official adapter."
  },
  {
    source_id: "chinafund-com-cn",
    source_name: "中国基金报/基金业公开资讯",
    source_type: "news",
    quality_tier: "medium",
    stability: "medium",
    coverage: ["fund_news", "industry_news", "manager_interviews"],
    recommended_for: ["secondary_evidence", "industry_news"],
    access_method: "public website / RSS where available",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "News is secondary evidence; avoid long copyrighted excerpts.",
    priority: 70,
    notes: "Useful for context only; never a core source for investment conclusions."
  },
  {
    source_id: "regulated-financial-media",
    source_name: "证券时报/中国证券报/上海证券报等财经媒体",
    source_type: "news",
    quality_tier: "medium",
    stability: "medium",
    coverage: ["industry_news", "fund_news", "market_commentary"],
    recommended_for: ["industry_news", "secondary_evidence"],
    access_method: "website / RSS if available",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "News is secondary evidence; obey copyright and quote limits.",
    priority: 80,
    notes: "Never use as sole basis for strong conclusions."
  },
  {
    source_id: "social-sentiment-sources",
    source_name: "雪球/股吧/论坛等社交情绪源",
    source_type: "social",
    quality_tier: "low",
    stability: "low",
    coverage: ["social_sentiment"],
    recommended_for: ["weak_sentiment_signal_only"],
    access_method: "public web / licensed API if available",
    requires_auth: true,
    is_demo: false,
    integration_status: "blocked",
    legal_note: "Never treat forum/social sentiment as core evidence; respect platform terms.",
    priority: 200,
    notes: "Weak optional signal only."
  },
  {
    source_id: "demo-fixture",
    source_name: "Demo Fixture Provider",
    source_type: "demo_fixture",
    quality_tier: "demo",
    stability: "high",
    coverage: ["demo_fund_meta", "demo_current_nav", "demo_nav_history"],
    recommended_for: ["local_demo", "tests"],
    access_method: "local fixture",
    requires_auth: false,
    is_demo: true,
    integration_status: "implemented",
    legal_note: "Must never be displayed as real data.",
    priority: 999,
    notes: "Only enabled with FUNDSENTINEL_DEMO_MODE=true."
  }
];

export function listDataSourceCatalog(): DataSourceCatalogEntry[] {
  return [...DATA_SOURCE_CATALOG].sort((a, b) => a.priority - b.priority);
}
