import type { DataSourceCatalogEntry } from "./sourceTypes.js";

export const DATA_SOURCE_CATALOG: DataSourceCatalogEntry[] = [
  {
    source_id: "csrc-fund-disclosure",
    source_name: "中国证监会基金电子披露网站",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_reports", "nav_disclosure", "xbrl", "legal_disclosure"],
    recommended_for: ["fund_reports", "official_fund_reports", "fund_meta", "official_evidence"],
    access_method: "official website / disclosure documents",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public disclosure documents respectfully; cache and rate-limit access.",
    priority: 1,
    notes: "Primary authoritative source for public fund disclosure. Provider now probes the official entrypoint and parses report links when reachable; site-protection failures are surfaced as data gaps."
  },
  {
    source_id: "csrc-official",
    source_name: "中国证监会官网",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["regulatory_rules", "market_supervision", "fund_regulation", "official_releases", "policy_evidence", "industry_news"],
    recommended_for: ["regulatory_context", "policy_evidence", "industry_news", "fund_rule_validation"],
    access_method: "official CSRC searchList JSON endpoint for official releases",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official releases with source URL and publication date.",
    priority: 2,
    notes: "Implemented for official CSRC release metadata and summaries from the public searchList endpoint. It is regulatory/policy context only, not a NAV or trading source."
  },
  {
    source_id: "csrc-public-fund-products",
    source_name: "中国证监会公募基金产品索引",
    source_type: "fund_meta",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_meta", "public_fund_product_index", "fund_establishment_date"],
    recommended_for: ["fund_meta", "industry_baseline", "manager_validation"],
    access_method: "official CSRC XLSX attachment: https://www.csrc.gov.cn/csrc/c101900/c1029655/content.shtml",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public statistics and disclose source timestamp.",
    priority: 3,
    notes: "Implemented through the official CSRC public fund product index XLSX. It validates fund code/name/establishment date only; NAV, holdings, reports, and manager detail remain separate sources."
  },
  {
    source_id: "amac-public-fund-data",
    source_name: "中国证券投资基金业协会",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_market_statistics", "industry_reports", "policy_evidence", "industry_news"],
    recommended_for: ["industry_baseline", "manager_validation", "policy_evidence", "industry_news", "Logos_policy_background"],
    access_method: "official public fund statistics page: https://www.amac.org.cn/sjtj/tjbg/gmjj/",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public statistics and disclose source timestamp.",
    priority: 4,
    notes:
      "Implemented for official monthly public-fund market-data PDF references as industry baseline evidence. It does not supply fund-specific NAV, holdings, or trading signals."
  },
  {
    source_id: "cninfo-report",
    source_name: "巨潮资讯网",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_announcements", "listed_fund_reports", "listed_fund_pdf_metadata", "fund_reports"],
    recommended_for: ["fund_reports", "official_fund_reports", "holdings_cross_check", "official_announcements"],
    access_method: "official endpoints: /new/data/fund_stock.json and /new/hisAnnouncement/query",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Respect official site rules; prefer documented query endpoints if available.",
    priority: 5,
    notes: "Implemented for listed funds covered by CNInfo fund_stock.json, such as ETF/LOF/closed-end funds. It uses precise code/orgId matching and verifies official PDF metadata; ordinary open-end funds may be outside this source's coverage."
  },
  {
    source_id: "fund-company-official-sites",
    source_name: "基金公司官网公告与净值披露",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_reports", "current_nav", "fund_meta", "announcements"],
    recommended_for: ["current_nav", "fund_reports", "official_fund_reports", "fund_meta"],
    access_method: "per-company website adapters",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Company sites differ; adapters need per-site maintenance and source timestamps.",
    priority: 5,
    notes: "Useful cross-check source; requires many adapters."
  },
  {
    source_id: "fund-company-report",
    source_name: "基金公司官方报告证据协调器",
    source_type: "fund_report",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_reports", "official_fund_reports", "official_pdf_metadata"],
    recommended_for: ["fund_reports", "official_fund_reports", "official_evidence", "holdings_cross_check"],
    access_method: "context coordinator over official fund-company/regulatory report documents",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Coordinates already collected official metadata only; does not fabricate reports or bypass source-site rules.",
    priority: 8,
    notes:
      "Consumes official report documents collected by concrete fund-company/regulatory providers and succeeds only when a verified official periodic-report PDF is already present."
  },
  {
    source_id: "cmfchina-fund-official",
    source_name: "招商基金官网官方公告与产品详情",
    source_type: "fund_report",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "nav_history", "official_company_notices", "report_notice_refs"],
    recommended_for: ["current_nav", "nav_history", "fund_reports", "official_fund_reports", "fund_meta", "official_evidence"],
    access_method: "official website adapter: https://www.cmfchina.com/web/fundDetail/{fund_code}/index.html",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official company pages respectfully; cache and rate-limit. Report prompt notices are not report bodies.",
    priority: 6,
    notes: "Implemented first per-company adapter. It records official notices/report prompts, parses SSR page NAV history for official-company cross-checking, and points to CSRC fund e-disclosure when referenced."
  },
  {
    source_id: "huaan-fund-official",
    source_name: "华安基金官网官方净值与披露",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings", "official_company_notices", "fund_reports"],
    recommended_for: ["current_nav", "nav_history", "fund_meta", "holdings", "fund_reports", "official_fund_reports", "official_evidence"],
    access_method: "official website adapter: https://www.huaan.com.cn/funds/{fund_code}/index.shtml and /funddetail/selectFundayByCode.do",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official company pages respectfully; cache and rate-limit. Cross-check report links against CSRC official disclosure when possible.",
    priority: 7,
    notes: "Second per-company official adapter. It parses official HuaAn fund pages, recent NAV table rows, holdings names, and disclosure links without treating unverified PDF bodies as parsed report text."
  },
  {
    source_id: "efund-official",
    source_name: "易方达基金官网官方净值与披露",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings", "official_company_notices", "fund_reports"],
    recommended_for: ["current_nav", "nav_history", "fund_meta", "holdings", "fund_reports", "official_fund_reports", "official_evidence"],
    access_method: "official website adapter: https://www.efunds.com.cn/fund/{fund_code}.shtml and https://cdn.efunds.com.cn/market/2.0/his/{fund_code}_all.js",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official company pages/CDN files respectfully; cache and rate-limit. Cross-check report links against CSRC official disclosure when possible.",
    priority: 7,
    notes:
      "Third per-company official adapter. It parses E Fund official product pages, official CDN NAV history, disclosed holdings, and announcement PDF links without treating PDF bodies as parsed report text."
  },
  {
    source_id: "eastmoney-fund",
    source_name: "东方财富/天天基金基金数据",
    source_type: "nav_history",
    quality_tier: "high",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "nav_history", "rankings", "fund_manager"],
    recommended_for: ["nav_history", "current_nav", "fund_meta"],
    access_method: "public web/API adapter or licensed API if available",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Confirm terms before automated use; cache and rate-limit.",
    priority: 10,
    notes: "Practical first target for NAV history, with official-source cross-check later."
  },
  {
    source_id: "eastmoney-fund-archive",
    source_name: "东方财富/天天基金基金档案",
    source_type: "holdings",
    quality_tier: "high",
    stability: "medium",
    coverage: ["holdings", "fund_reports", "asset_allocation"],
    recommended_for: ["holdings", "fund_report_hints", "cross_source_validation"],
    access_method: "public fund archive pages",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Confirm terms before automated use; cache, rate-limit, and cross-check against official reports.",
    priority: 13,
    notes: "Parses public archive tables for stock and bond holdings."
  },
  {
    source_id: "eastmoney-nav-history",
    source_name: "东方财富/天天基金历史净值明细",
    source_type: "nav_history",
    quality_tier: "high",
    stability: "medium",
    coverage: ["current_nav", "nav_history", "nav_history_dates", "purchase_redeem_status"],
    recommended_for: ["nav_history", "current_nav", "cross_source_validation"],
    access_method: "public F10 NAV endpoint: https://api.fund.eastmoney.com/f10/lsjz",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Confirm terms before automated use; cache, rate-limit, and cross-check against official fund company NAV disclosures.",
    priority: 11,
    notes: "Second implemented NAV path for cross-checking the page JavaScript provider. Not an official fund-company source."
  },
  {
    source_id: "eastmoney-fund-announcement",
    source_name: "东方财富/天天基金基金公告索引",
    source_type: "fund_report",
    quality_tier: "high",
    stability: "medium",
    coverage: ["fund_reports", "periodic_report_index", "announcement_dates"],
    recommended_for: ["fund_report_refs", "report_freshness", "official_report_discovery"],
    access_method: "public F10 announcement API",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use as a public report index only; cross-check and fetch official disclosure PDFs before strong conclusions.",
    priority: 14,
    notes: "Finds periodic report announcements and IDs, but does not yet parse official report bodies."
  },
  {
    source_id: "manual-csv-import",
    source_name: "人工 CSV 导入",
    source_type: "manual_import",
    quality_tier: "high",
    stability: "high",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings"],
    recommended_for: ["fund_meta", "nav_history", "current_nav", "portfolio_holdings", "bootstrap_validation"],
    access_method: "user/operator upload",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Requires audit trail, file checksum, source declaration, and import timestamp.",
    priority: 20,
    notes: "Implemented as explicit local CSV directory fallback via FUNDSENTINEL_MANUAL_CSV_DIR. Best short-term way to validate real-data flow without scraping."
  },
  {
    source_id: "manual-official-report-import",
    source_name: "人工官方报告 PDF 导入",
    source_type: "manual_import",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["fund_reports", "official_fund_reports", "official_pdf_metadata"],
    recommended_for: ["fund_reports", "official_fund_reports", "official_evidence", "manual_workaround"],
    access_method: "verified local PDF manifest via FUNDSENTINEL_MANUAL_REPORT_DIR",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Requires official source URL, local PDF file, SHA256 checksum, import timestamp, and operator/source audit trail.",
    priority: 21,
    notes:
      "Implemented as explicit local manifest fallback for official report PDFs when automated official sites are blocked or coverage is incomplete. It verifies PDF file signature and SHA256 but does not parse report body text."
  },
  {
    source_id: "gov-cn-policy",
    source_name: "中国政府网最新政策",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["latest_policy", "macro_policy_context", "policy_evidence"],
    recommended_for: ["policy_evidence", "macro_context", "Logos_policy_background"],
    access_method: "official JSON endpoint: https://www.gov.cn/zhengce/zuixin/ZUIXINZHENGCE.json",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public policy metadata with publication date and URL; do not infer fund-specific conclusions directly.",
    priority: 28,
    notes: "Maps latest official national policy titles to broad fund themes as weak policy background evidence."
  },
  {
    source_id: "policy-news",
    source_name: "官方政策与行业新闻",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["policy_evidence", "industry_news", "industry_policy"],
    recommended_for: ["policy_evidence", "industry_news", "industry_logic", "Logos_policy_background"],
    access_method: "official NDRC news page: https://www.ndrc.gov.cn/xwdt/xwfb/",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public releases with source URL and publication date; treat as supporting evidence only.",
    priority: 30,
    notes: "Implemented for the NDRC official news-release list. If official sites return WAF/403 responses, provider failures are surfaced in DataGapReport."
  },
  {
    source_id: "csi-index",
    source_name: "中证指数有限公司",
    source_type: "index_data",
    quality_tier: "high",
    stability: "high",
    coverage: ["index_constituents", "index_history", "index_methodology"],
    recommended_for: ["benchmark", "theme_validation", "industry_mapping"],
    access_method: "official website / licensed data",
    requires_auth: true,
    is_demo: false,
    integration_status: "requires_license",
    legal_note: "Index history/constituents may require license for systematic use.",
    priority: 30,
    notes: "Important for benchmark and theme fund validation."
  },
  {
    source_id: "sse-szse-official",
    source_name: "上交所/深交所官方网站",
    source_type: "news",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["exchange_announcements", "trading_calendar", "market_rules"],
    recommended_for: ["market_calendar", "official_market_events", "policy_evidence", "industry_news"],
    access_method:
      "official SSE market-calendar endpoints plus SZSE official news/notice pages: https://www.sse.com.cn/disclosure/dealinstruc/calendar/index.shtml and https://www.szse.cn/aboutus/trends/news/",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public official releases with timestamps and links.",
    priority: 35,
    notes:
      "Implemented for Shanghai Stock Exchange official market-calendar events and Shenzhen Stock Exchange official news/notice pages. Exchange events are context only, not NAV, holdings, reports, or advice."
  },
  {
    source_id: "official-policy-sites",
    source_name: "国务院/发改委/工信部/央行/统计局等官方政策数据",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["policy_evidence", "macro_data", "industry_policy"],
    recommended_for: ["policy_evidence", "macro_context", "industry_logic"],
    access_method: "official websites and public releases",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Prefer official pages; keep publication date and URL.",
    priority: 40,
    notes: "Primary source for Logos hard logic evidence."
  },
  {
    source_id: "ndrc-official",
    source_name: "国家发展改革委",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["industry_policy", "macro_policy", "investment_policy"],
    recommended_for: ["policy_evidence", "industry_logic"],
    access_method: "official website",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use official public releases with publication date and URL.",
    priority: 41,
    notes: "Important for industry direction and policy-side hard logic."
  },
  {
    source_id: "miit-official",
    source_name: "工业和信息化部",
    source_type: "policy",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["policy_evidence", "industry_news", "manufacturing_policy", "digital_economy", "industry_data"],
    recommended_for: ["policy_evidence", "industry_news", "industry_logic", "theme_validation"],
    access_method: "official homepage static policy/data lists: https://www.miit.gov.cn/index.html",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public releases with publication date and URL.",
    priority: 42,
    notes:
      "Implemented by parsing MIIT official homepage policy-file, policy-interpretation, industry-data, industry-news, and consultation/publication lists. It is supporting evidence only, not fund NAV, holdings, reports, or advice."
  },
  {
    source_id: "pbc-official",
    source_name: "中国人民银行",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["monetary_policy", "rates", "liquidity", "financial_statistics"],
    recommended_for: ["macro_context", "bond_fund_context", "risk_context"],
    access_method: "official money statistics HTML: https://www.pbc.gov.cn/diaochatongjisi/116219/116319/5570903/5570886/index.html",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public statistics and releases with timestamps.",
    priority: 43,
    notes: "Implemented for official PBC Money Supply monthly HTML tables, including M2/M1/M0 liquidity indicators. Macro context only."
  },
  {
    source_id: "stats-gov-cn",
    source_name: "国家统计局",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "macro_statistics", "industry_statistics", "economic_indicators"],
    recommended_for: ["macro_context", "industry_logic"],
    access_method: "official National Data endpoint probe: https://data.stats.gov.cn/easyquery.htm",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public statistics and keep release date.",
    priority: 44,
    notes: "Implemented as an official endpoint probe/parser. Site protection or blocked access is surfaced as a data gap instead of being bypassed."
  },
  {
    source_id: "mof-official",
    source_name: "财政部",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "fiscal_policy", "government_bonds", "budget_data", "fiscal_revenue_expenditure"],
    recommended_for: ["macro_context", "bond_fund_context", "policy_evidence"],
    access_method: "official MOF fiscal revenue/expenditure page: https://www.mof.gov.cn/zhengwuxinxi/redianzhuanti/quanguocaizhengshouzhiqingkuang/",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public releases with source URL and publication date.",
    priority: 45,
    notes: "Implemented for official monthly national fiscal revenue/expenditure releases. Budget documents and government-bond issuance tables remain future extensions."
  },
  {
    source_id: "safe-official",
    source_name: "国家外汇管理局",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "fx_data", "official_reserve_assets", "cross_border_capital", "balance_of_payments"],
    recommended_for: ["qdii_context", "macro_context"],
    access_method: "official SAFE reserve-assets HTML list: https://www.safe.gov.cn/safe/gfcbzc/index.html",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official public statistics and keep release date.",
    priority: 46,
    notes: "Implemented for official reserve-asset monthly USD indicators. Additional balance-of-payments and capital-flow tables remain future extensions."
  },
  {
    source_id: "commercial-terminal-api",
    source_name: "Wind/Choice/Tushare/其他授权数据 API",
    source_type: "nav_history",
    quality_tier: "high",
    stability: "high",
    coverage: ["fund_meta", "current_nav", "nav_history", "holdings", "fund_manager", "benchmark"],
    recommended_for: ["fund_meta", "current_nav", "nav_history", "holdings", "benchmark", "production_data", "cross_source_validation"],
    access_method: "licensed API",
    requires_auth: true,
    is_demo: false,
    integration_status: "requires_license",
    legal_note: "Use only with proper license and credentials; never hardcode keys.",
    priority: 50,
    notes: "Likely production-grade path if budget allows."
  },
  {
    source_id: "sec-edgar",
    source_name: "SEC EDGAR",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["us_fund_filings", "etf_filings", "n_port", "n_cen", "prospectus"],
    recommended_for: ["qdii_context", "official_fund_reports", "official_evidence", "cross_border_fund_disclosure"],
    access_method: "official SEC EDGAR APIs and filing documents",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use SEC published access rules, identify the application, cache responses, and keep filing URLs.",
    priority: 51,
    notes: "Authoritative overseas disclosure source for US-listed ETFs/funds and QDII cross-checks."
  },
  {
    source_id: "hkex-official",
    source_name: "香港交易所披露易与市场资料",
    source_type: "regulatory_disclosure",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["hk_announcements", "hk_etf_disclosure", "market_calendar"],
    recommended_for: ["qdii_context", "official_announcements", "cross_border_fund_disclosure"],
    access_method: "official HKEX websites and data products",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Use public disclosure pages respectfully; licensed data products may be required for systematic market data.",
    priority: 52,
    notes: "Important for Hong Kong market exposure and QDII/H shares context."
  },
  {
    source_id: "fred-official",
    source_name: "FRED Federal Reserve Economic Data",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "us_rates", "inflation", "employment", "liquidity", "macro_time_series"],
    recommended_for: ["macro_context", "qdii_context", "bond_fund_context", "risk_context"],
    access_method: "official FRED API: https://api.stlouisfed.org/fred/series/observations",
    requires_auth: true,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use official API key via environment configuration only; keep series IDs and observation dates.",
    priority: 53,
    notes: "Implemented as a credentialed official macro provider. Missing FRED_API_KEY or FUNDSENTINEL_FRED_API_KEY is surfaced as an explicit provider failure, never replaced with fabricated data."
  },
  {
    source_id: "world-bank-api",
    source_name: "World Bank Open Data",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "country_macro", "growth", "population", "development_indicators"],
    recommended_for: ["macro_context", "country_context", "industry_logic"],
    access_method: "official World Bank API",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Keep indicator IDs, country codes, and source timestamps.",
    priority: 54,
    notes: "Implemented for a small official macro baseline: GDP growth, CPI inflation, and real interest rate for configured countries."
  },
  {
    source_id: "imf-data-api",
    source_name: "IMF Data",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "global_macro", "world_economic_outlook", "growth", "inflation", "employment"],
    recommended_for: ["macro_context", "qdii_context", "country_context"],
    access_method: "official IMF DataMapper API: https://www.imf.org/external/datamapper/api/v2",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Use public datasets with dataset code, series key, and observation date.",
    priority: 55,
    notes: "Implemented for selected DataMapper/WEO macro series such as real GDP growth, CPI inflation, and unemployment. It is macro context only, not fund NAV or holdings evidence."
  },
  {
    source_id: "oecd-data-api",
    source_name: "OECD Data",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["oecd_macro", "industry_statistics", "policy_indicators"],
    recommended_for: ["macro_context", "industry_logic", "country_context"],
    access_method: "official OECD API / SDMX services",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Keep dataset identifiers, dimensions, release date, and query URL.",
    priority: 56,
    notes: "Useful for developed-market macro and industry comparison."
  },
  {
    source_id: "eurostat-api",
    source_name: "Eurostat",
    source_type: "macro_data",
    quality_tier: "authoritative",
    stability: "high",
    coverage: ["macro_data", "eu_macro", "growth", "labor_market", "official_statistics"],
    recommended_for: ["macro_context", "qdii_context", "country_context"],
    access_method: "official Eurostat Statistics API: https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
    requires_auth: false,
    is_demo: false,
    integration_status: "implemented",
    legal_note: "Keep dataset code, filters, release date, and query URL.",
    priority: 57,
    notes: "Implemented for selected stable annual JSON-stat series such as EU real GDP growth and euro-area unemployment. Inflation remains a planned extension until the latest HICP dimension mapping is added."
  },
  {
    source_id: "nasdaq-data-link",
    source_name: "Nasdaq Data Link",
    source_type: "market_data",
    quality_tier: "high",
    stability: "high",
    coverage: ["licensed_market_data", "etf_data", "economic_data", "alternative_datasets"],
    recommended_for: ["production_data", "market_data", "cross_source_validation"],
    access_method: "licensed API",
    requires_auth: true,
    is_demo: false,
    integration_status: "requires_license",
    legal_note: "Use only with proper license and API key from environment configuration.",
    priority: 58,
    notes: "Potential licensed production source; should not be assumed available in open-source mode."
  },
  {
    source_id: "fund-company-site-adapters",
    source_name: "头部基金公司官网适配器集合",
    source_type: "fund_company",
    quality_tier: "authoritative",
    stability: "medium",
    coverage: ["fund_meta", "current_nav", "official_notices", "report_notice_refs"],
    recommended_for: ["official_company_cross_check", "fund_reports", "official_fund_reports", "fund_meta", "current_nav"],
    access_method: "per-company official website adapters",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "Each adapter must respect website terms, rate-limit, and keep source URLs.",
    priority: 60,
    notes: "Planned expansion path after the first CMF China official adapter."
  },
  {
    source_id: "chinafund-com-cn",
    source_name: "中国基金报/基金业公开资讯",
    source_type: "news",
    quality_tier: "medium",
    stability: "medium",
    coverage: ["fund_news", "industry_news", "manager_interviews"],
    recommended_for: ["secondary_evidence", "industry_news"],
    access_method: "public website / RSS where available",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "News is secondary evidence; avoid long copyrighted excerpts.",
    priority: 70,
    notes: "Useful for context only; never a core source for investment conclusions."
  },
  {
    source_id: "regulated-financial-media",
    source_name: "证券时报/中国证券报/上海证券报等财经媒体",
    source_type: "news",
    quality_tier: "medium",
    stability: "medium",
    coverage: ["industry_news", "fund_news", "market_commentary"],
    recommended_for: ["industry_news", "secondary_evidence"],
    access_method: "website / RSS if available",
    requires_auth: false,
    is_demo: false,
    integration_status: "planned",
    legal_note: "News is secondary evidence; obey copyright and quote limits.",
    priority: 80,
    notes: "Never use as sole basis for strong conclusions."
  },
  {
    source_id: "social-sentiment-sources",
    source_name: "雪球/股吧/论坛等社交情绪源",
    source_type: "social",
    quality_tier: "low",
    stability: "low",
    coverage: ["social_sentiment"],
    recommended_for: ["weak_sentiment_signal_only"],
    access_method: "public web / licensed API if available",
    requires_auth: true,
    is_demo: false,
    integration_status: "blocked",
    legal_note: "Never treat forum/social sentiment as core evidence; respect platform terms.",
    priority: 200,
    notes: "Weak optional signal only."
  },
  {
    source_id: "demo-fixture",
    source_name: "Demo Fixture Provider",
    source_type: "demo_fixture",
    quality_tier: "demo",
    stability: "high",
    coverage: ["demo_fund_meta", "demo_current_nav", "demo_nav_history"],
    recommended_for: ["local_demo", "tests"],
    access_method: "local fixture",
    requires_auth: false,
    is_demo: true,
    integration_status: "implemented",
    legal_note: "Must never be displayed as real data.",
    priority: 999,
    notes: "Only enabled with FUNDSENTINEL_DEMO_MODE=true."
  }
];

export function listDataSourceCatalog(): DataSourceCatalogEntry[] {
  return [...DATA_SOURCE_CATALOG].sort((a, b) => a.priority - b.priority);
}
